# Global Settings
kubernetes:
  kubeconfig: ""

webhook:
  enabled: true
  port: 8080
  secret: "my-very-secret-key"

repositories:
  - name: "payments-team"
    url: "https://github.com/MyoMyatMin/payments-api-mock.git"
    branch: "main"
    path: "manifests"
    namespace: "prod-backend"
    interval: 60s
    prune: true

  - name: "frontend-team"
    url: "https://github.com/MyoMyatMin/marketing-site-mock.git"
    branch: "main"
    path: "k8s"
    namespace: "prod-frontend"
    interval: 60s
    prune: true
